/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import DAO.DocGiaDAO;
import Models.DocGia;
import com.mycompany.testmysql.Run;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ChangeEvent;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ADMIN
 */
public class QuanLyDocGia_UI extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyDocGia_UI
     */
    private DefaultTableModel tbModelDocGia;
    private List<DocGia> DGSeacrh;
    public QuanLyDocGia_UI() {
        initComponents();
        ShowdataDocGia();
        //Set tên NV
        String text = "Xin chào,"+Run.tk.getHoTenNV();
        lblQTV.setText(text);
        //Set thời gian
        Clock clock= new Clock(); 
        clock.start();
        btnLuuDG.setEnabled(false);
        
        setFontTable(tbDocGia);
    }
    
    SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
    public class Clock extends Thread{ 
    public Clock(){    } 
    @Override
    public void run(){ 
        while(true){ 
            Calendar calendar = Calendar.getInstance();                
            String str;  
            str= sdf.format(calendar.getTime()); 
            lblTime.setText(str); 
        try{ 
            sleep(1000); 
          } catch(Exception e){ 
             System.out.println(e); 
            } 
      } 
    }
    }

    public void cleardataDocGia()
    {
        while (tbModelDocGia.getRowCount()>0) {
            tbModelDocGia.removeRow(0);
            
        }
    }
    
    
    private void ShowdataDocGia()
    {
        //setup tbmodel 
        tbModelDocGia = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return row == 0;
            }
         };
        String[] tencot = {"Mã Độc Giả", "Tên Độc Giả", "Địa Chỉ", "Email", "Số Điện Thoai", "Ngày Sinh"};
        tbModelDocGia.setColumnIdentifiers(tencot);
        tbDocGia.setModel(tbModelDocGia);
        cleardataDocGia();
        
        
        
        //setupdata
        DocGiaDAO ds = new DocGiaDAO();
        List<DocGia> abc = ds.getAllDocGia();
        for (int i = 0; i < abc.size(); i++) {
            String[] row = {
                String.valueOf(abc.get(i).getMaDocGia()),
                abc.get(i).getHoTen(),
                abc.get(i).getDiaChi(),
                abc.get(i).getEmail(),
                abc.get(i).getSDT(),
                String.valueOf(abc.get(i).getNgaySinh()),
            };
            tbModelDocGia.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblQTV = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaDG = new javax.swing.JTextField();
        txtTenDG = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        dateChooser1 = new datechooser.beans.DateChooserCombo();
        jPanel13 = new javax.swing.JPanel();
        btnThemDG = new javax.swing.JButton();
        btnSuaDG = new javax.swing.JButton();
        btnXoaDG = new javax.swing.JButton();
        btnTimKiemDG = new javax.swing.JButton();
        btnLamMoiDG = new javax.swing.JButton();
        btnLuuDG = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbDocGia = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1062, 802));
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Quản lý độc giả");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 230, 50));

        lblQTV.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        lblQTV.setForeground(new java.awt.Color(255, 255, 255));
        lblQTV.setText("Xin chào");
        jPanel1.add(lblQTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 200, 20));

        lblTime.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("jLabel5");
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 180, -1));

        btnHome.setBackground(new java.awt.Color(0, 153, 153));
        btnHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnHomeMouseDragged(evt);
            }
        });
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Trang chủ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_home_40px.png"))); // NOI18N

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(15, 15, 15))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 155, -1));

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("                                                                                              Thông tin độc giả");
        jPanel10.add(jLabel8, java.awt.BorderLayout.NORTH);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel9.setText("Email :");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel10.setText("Mã độc giả :");

        txtMaDG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMaDG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaDGKeyPressed(evt);
            }
        });

        txtTenDG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTenDG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenDGKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel11.setText("Tên độc giả :");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel12.setText("Số điện thoại :");

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel13.setText("Ngày sinh :");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel15.setText("Địa chỉ :");

        txtDiaChi.setColumns(20);
        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDiaChi.setLineWrap(true);
        txtDiaChi.setRows(5);
        txtDiaChi.setWrapStyleWord(true);
        txtDiaChi.setAutoscrolls(false);
        txtDiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiaChiKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtDiaChi);

        dateChooser1.setCalendarBackground(new java.awt.Color(133, 140, 148));
        dateChooser1.setFieldFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 15));
        dateChooser1.setNavigateFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11));
        dateChooser1.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_PERIOD);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(29, 29, 29)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaDG)
                    .addComponent(txtTenDG)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(dateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaDG)
                    .addComponent(jLabel9)
                    .addComponent(txtEmail)
                    .addComponent(jLabel10))
                .addGap(17, 17, 17)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTenDG)
                    .addComponent(txtSDT)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)))
                    .addComponent(dateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        btnThemDG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnThemDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_plus_+_30px_1.png"))); // NOI18N
        btnThemDG.setText("Thêm");
        btnThemDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDGActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel13.add(btnThemDG, gridBagConstraints);

        btnSuaDG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSuaDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_edit_file_30px.png"))); // NOI18N
        btnSuaDG.setText("Sửa");
        btnSuaDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDGActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel13.add(btnSuaDG, gridBagConstraints);

        btnXoaDG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnXoaDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_30px.png"))); // NOI18N
        btnXoaDG.setText("Xóa");
        btnXoaDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDGActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel13.add(btnXoaDG, gridBagConstraints);

        btnTimKiemDG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnTimKiemDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_30px.png"))); // NOI18N
        btnTimKiemDG.setText("Tìm kiếm");
        btnTimKiemDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemDGActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel13.add(btnTimKiemDG, gridBagConstraints);

        btnLamMoiDG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnLamMoiDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_reset_30px.png"))); // NOI18N
        btnLamMoiDG.setText("Làm mới");
        btnLamMoiDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiDGActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel13.add(btnLamMoiDG, gridBagConstraints);

        btnLuuDG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnLuuDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_save_close_30px.png"))); // NOI18N
        btnLuuDG.setText("Lưu");
        btnLuuDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuDGActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel13.add(btnLuuDG, gridBagConstraints);

        jPanel10.add(jPanel13, java.awt.BorderLayout.SOUTH);

        jPanel4.add(jPanel10, java.awt.BorderLayout.NORTH);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        tbDocGia.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        tbDocGia.setMinimumSize(new java.awt.Dimension(20, 20));
        tbDocGia.setRowHeight(25);
        tbDocGia.setSelectionBackground(new java.awt.Color(0, 255, 204));
        tbDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDocGiaMouseClicked(evt);
            }
        });
        tbDocGia.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tbDocGiaInputMethodTextChanged(evt);
            }
        });
        tbDocGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbDocGiaKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tbDocGia);

        jPanel12.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        setColorHome(btnHome);
        this.setVisible(false);
        Run.Home();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeMouseDragged

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        setColorHome(btnHome);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        resetColorHome(btnHome);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnLuuDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuDGActionPerformed
        // TODO add your handling code here:
        if(btnThemDG.isEnabled())
        {            
            try {
                String Name_PATTERN = "^[\\p{L}\\p{M}' \\.\\-]+$";
                Pattern p = Pattern.compile(Name_PATTERN);
                if(p.matcher(txtTenDG.getText()).find()){
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Tên độc giả chỉ bao gồm chữ cái, xin nhập lại Tên độc giả");
                    return;
                }
                StringBuffer sb = new StringBuffer();
                if(txtMaDG.getText().equals("")){
                    sb.append("Mã đầu sách không được trống");
                    
                }
                if(sb.length()>0){
                    JOptionPane.showMessageDialog(this, sb);
                    return;
                }
                if(txtSDT.getText().length()>10 || txtSDT.getText().length()<10){
                    JOptionPane.showMessageDialog(this, "Số điện thoại phải có 10 số");
                    return;
                }
                try {
                    int n = Integer.parseInt(txtSDT.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "nhập lại số điện thoại");
                    return;
                }
                String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
                Pattern pa = Pattern.compile(EMAIL_PATTERN);
                if(pa.matcher(txtEmail.getText()).find()){
                    
                }else{
                    JOptionPane.showMessageDialog(this, "nhập lại Email");
                    return;
                }
                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                dateChooser1.setDateFormat(df);
                Date NS =  df.parse(dateChooser1.getText());
                DocGia dg = new DocGia();
                dg.setMaDocGia(txtMaDG.getText());
                dg.setHoTen(txtTenDG.getText());                
                dg.setDiaChi(txtDiaChi.getText());
                dg.setEmail(txtEmail.getText());
                dg.setSDT(txtSDT.getText());
                dg.setNgaySinh(NS);
                DocGiaDAO na = new DocGiaDAO();
                na.insert(dg);
                JOptionPane.showMessageDialog(this, "Thêm mới thành công");
                ShowdataDocGia();
            } catch (Exception e) {
                if(e.getMessage().equals("Duplicate entry '"+txtMaDG.getText()+"' for key 'PRIMARY'")){
                    JOptionPane.showMessageDialog(this, "Mã độc giả đã tồn tại vui lòng nhập lại");
                }
                System.err.println("Loi:" + e.getMessage());
                
            }
        }else if(btnSuaDG.isEnabled()){
                
            try {
                String Name_PATTERN = "^[\\p{L}\\p{M}' \\.\\-]+$";
                Pattern p = Pattern.compile(Name_PATTERN);
                if(p.matcher(txtTenDG.getText()).find()){
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Tên độc giả chỉ bao gồm chữ cái, xin nhập lại Tên độc giả ");
                    return;
                }
                StringBuffer sb = new StringBuffer();
                if(txtMaDG.getText().equals("")){
                        sb.append("Mã đầu sách không được trống");

                }
                if(sb.length()>0){
                    JOptionPane.showMessageDialog(this, sb);
                    return;
                }
                if(txtSDT.getText().length()>10 || txtSDT.getText().length()<10){
                    JOptionPane.showMessageDialog(this, "Số điện thoại phải có 10 số");
                    return;
                }
                try {
                    int n = Integer.parseInt(txtSDT.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "nhập lại số điện thoại");
                    return;
                }
                String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
                Pattern pa = Pattern.compile(EMAIL_PATTERN);
                if(pa.matcher(txtEmail.getText()).find()){
                    
                }else{
                    JOptionPane.showMessageDialog(this, "nhập lại Email");
                    return;
                }
                DocGia dg = new DocGia();
                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                dateChooser1.setDateFormat(df);
                Date NS =  df.parse(dateChooser1.getText());
                dg.setMaDocGia(txtMaDG.getText());
                dg.setHoTen(txtTenDG.getText());                
                dg.setDiaChi(txtDiaChi.getText());
                dg.setEmail(txtEmail.getText());
                dg.setSDT(txtSDT.getText());
                dg.setNgaySinh(NS);
                
                DocGiaDAO na = new DocGiaDAO();
                na.update(dg);
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                ShowdataDocGia();
            } catch (Exception e) {
                System.out.println(e.getMessage());
                e.printStackTrace();
            }
        }else if(btnXoaDG.isEnabled()){
            String ml = txtMaDG.getText();
            StringBuilder sb = new StringBuilder();
            if(ml.equals("")){
                JOptionPane.showMessageDialog(this, "Mã độc giả không được trống");
                txtMaDG.setBackground(Color.red);
            }
            else{
                DocGiaDAO na = new DocGiaDAO();
                boolean kt = na.delete(txtMaDG.getText());
                if(kt==true)
                {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                }else{
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                }
                ShowdataDocGia();
            }
        }
        
    }//GEN-LAST:event_btnLuuDGActionPerformed

    private void btnSuaDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDGActionPerformed
        // TODO add your handling code here:
        btnThemDG.setEnabled(false);
        btnXoaDG.setEnabled(false);
        btnTimKiemDG.setEnabled(false);
        txtMaDG.setEditable(false);
        btnLuuDG.setEnabled(true);
    }//GEN-LAST:event_btnSuaDGActionPerformed

    private void btnLamMoiDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiDGActionPerformed
        // TODO add your handling code here:
        btnXoaDG.setEnabled(true);
        btnTimKiemDG.setEnabled(true);
        btnSuaDG.setEnabled(true);
        btnThemDG.setEnabled(true);
        btnLuuDG.setEnabled(false);
        txtMaDG.setEditable(true);
        txtMaDG.setText("");
        txtTenDG.setText("");
        txtDiaChi.setText("");
        txtEmail.setText("");
        txtSDT.setText("");
        ShowdataDocGia();
    }//GEN-LAST:event_btnLamMoiDGActionPerformed

    private void btnTimKiemDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemDGActionPerformed

        btnLuuDG.setEnabled(true);
        btnSuaDG.setEnabled(true);
        btnThemDG.setEnabled(false);
        btnXoaDG.setEnabled(true);
        if(txtMaDG.getText().equals("") &&txtTenDG.getText().equals("") &&txtDiaChi.getText().equals("") && txtEmail.getText().equals("") && txtSDT.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Nhập ít nhất 1 thông tin tìm kiếm");
            }else{
                try {
                    cleardataDocGia();
                    DocGiaDAO dao = new DocGiaDAO();
                    List<DocGia> data = dao.SearchDG(txtMaDG.getText().toString(),txtTenDG.getText().toString(),txtDiaChi.getText().toString(), txtEmail.getText().toString(),txtSDT.getText().toString());
                    for (int i = 0; i < data.size(); i++) {
                        String[] row = {
                        String.valueOf(data.get(i).getMaDocGia()),
                        data.get(i).getHoTen(),
                        data.get(i).getDiaChi(),
                        data.get(i).getEmail(),
                        data.get(i).getSDT(),
                        String.valueOf(data.get(i).getNgaySinh()),

                    };
                    tbModelDocGia.addRow(row);

                }
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                    JOptionPane.showMessageDialog(this, "Không có kết quả phù hợp");

                }
            }
    }//GEN-LAST:event_btnTimKiemDGActionPerformed

    private void btnXoaDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDGActionPerformed
        // TODO add your handling code here:
        btnTimKiemDG.setEnabled(false);
        btnSuaDG.setEnabled(false);
        btnThemDG.setEnabled(false);
        btnLuuDG.setEnabled(true);
    }//GEN-LAST:event_btnXoaDGActionPerformed

    private void btnThemDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDGActionPerformed
        // TODO add your handling code here:
        btnSuaDG.setEnabled(false);
        btnXoaDG.setEnabled(false);
        btnTimKiemDG.setEnabled(false);
        txtMaDG.setEditable(true);
        btnLuuDG.setEnabled(true);
    }//GEN-LAST:event_btnThemDGActionPerformed

    private void tbDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDocGiaMouseClicked
        // TODO add your handling code here:
        int row = tbDocGia.getSelectedRow();
        if(row >= 0)
        {
            txtMaDG.setText(tbDocGia.getValueAt(row, 0).toString());
            txtTenDG.setText(tbDocGia.getValueAt(row, 1).toString());
            txtDiaChi.setText(tbDocGia.getValueAt(row, 2).toString());
            txtEmail.setText(tbDocGia.getValueAt(row, 3).toString());
            txtSDT.setText(tbDocGia.getValueAt(row, 4).toString());
            dateChooser1.setText(tbDocGia.getValueAt(row, 5).toString());
        }
    }//GEN-LAST:event_tbDocGiaMouseClicked

    private void tbDocGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbDocGiaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDocGiaKeyPressed

    private void tbDocGiaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tbDocGiaInputMethodTextChanged

    }//GEN-LAST:event_tbDocGiaInputMethodTextChanged

    private void txtMaDGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaDGKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtTenDG.requestFocus();
        }
    }//GEN-LAST:event_txtMaDGKeyPressed

    private void txtTenDGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDGKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtDiaChi.requestFocus();
        }
    }//GEN-LAST:event_txtTenDGKeyPressed

    private void txtDiaChiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaChiKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtEmail.requestFocus();
        }
    }//GEN-LAST:event_txtDiaChiKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtSDT.requestFocus();
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    /**
     * @param args the command line arguments
     */
    public void setColorHome(JPanel panel){
        panel.setBackground(new Color(153,255,255));
    }
    
    public void resetColorHome(JPanel panel){
        panel.setBackground(new Color(0,153,153));
    }

    private void setFontTable(JTable t){
        Font myFont = new Font("Serif", Font.PLAIN, 16);
        JTableHeader hd1 = t.getTableHeader();
        hd1.setFont(myFont);
    }
    

            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnHome;
    private javax.swing.JButton btnLamMoiDG;
    private javax.swing.JButton btnLuuDG;
    private javax.swing.JButton btnSuaDG;
    private javax.swing.JButton btnThemDG;
    private javax.swing.JButton btnTimKiemDG;
    private javax.swing.JButton btnXoaDG;
    private datechooser.beans.DateChooserCombo dateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblQTV;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tbDocGia;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaDG;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenDG;
    // End of variables declaration//GEN-END:variables
}
