/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import DAO.NhanVienDAO;
import Models.NhanVien;
import com.mycompany.testmysql.Run;
import de.mkammerer.argon2.Argon2;
import de.mkammerer.argon2.Argon2Factory;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ADMIN
 */
public class QuanLyNhanVien_UI extends javax.swing.JFrame {
    Argon2 argon2 = Argon2Factory.create(Argon2Factory.Argon2Types.ARGON2id, 32, 64);
    /**
     * Creates new form QuanLyNhanVien_UI
     */
    private final DefaultTableModel tbModelNhanVien = new DefaultTableModel();
    public QuanLyNhanVien_UI() {
        initComponents();
        
        //Set tên NV
        String text = "Xin chào,"+Run.tk.getHoTenNV();
        lblQTV.setText(text);
        //Set thời gian
        Clock clock= new Clock(); 
        clock.start();
        btnLuuNV.setEnabled(false);
        ShowdataNhanVien();
        
        setFontTable(tbNhanVien);
    }
    public void cleardataNhanVien()
    {
        while (tbModelNhanVien.getRowCount()>0) {
            tbModelNhanVien.removeRow(0);
            
        }
    }
    private void ShowdataNhanVien()
    {
        String[] tencot = {"Mã Nhân Viên", "Họ Tên Nhân Viên", "Ngày Sinh", "Địa Chỉ", "Số Điện Thoai"};
        tbModelNhanVien.setColumnIdentifiers(tencot);
        tbNhanVien.setModel(tbModelNhanVien);
        cleardataNhanVien();
        NhanVienDAO nv = new NhanVienDAO();
        List<NhanVien> data = nv.getNhanVien();
        for (int i = 0; i < data.size(); i++) {
            String[] row = {
                data.get(i).getIdNhanVien(),
                data.get(i).getHoTenNV(),
                String.valueOf(data.get(i).getNgaySinh()),
                data.get(i).getDiaChi(),
                data.get(i).getSDT(),               
            };
            tbModelNhanVien.addRow(row);
        }
    }
    SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
    public class Clock extends Thread{ 
    public Clock(){    } 
    @Override
    public void run(){ 
        while(true){ 
            Calendar calendar = Calendar.getInstance();                
            String str;  
            str= sdf.format(calendar.getTime()); 
            lblTime.setText(str); 
        try{ 
            sleep(1000); 
          } catch(Exception e){ 
             System.out.println(e); 
            } 
      } 
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSDTNV = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChiNV = new javax.swing.JTextArea();
        dateChooser1 = new datechooser.beans.DateChooserCombo();
        jPanel13 = new javax.swing.JPanel();
        btnThemNV = new javax.swing.JButton();
        btnSuaNV = new javax.swing.JButton();
        btnXoaNV = new javax.swing.JButton();
        btnTimKiemNV = new javax.swing.JButton();
        btnLamMoiNV = new javax.swing.JButton();
        btnLuuNV = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbNhanVien = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblQTV = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("                                                                                              Thông tin nhân viên");
        jPanel10.add(jLabel8, java.awt.BorderLayout.NORTH);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel9.setText("Mật khẩu :");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel10.setText("Mã nhân viên :");

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMaNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaNVKeyPressed(evt);
            }
        });

        txtTenNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTenNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenNVKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel11.setText("Tên nhân viên :");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel12.setText("Số điện thoại :");

        txtSDTNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel13.setText("Ngày sinh :");

        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMatKhauKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel15.setText("Địa chỉ :");

        txtDiaChiNV.setColumns(20);
        txtDiaChiNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDiaChiNV.setLineWrap(true);
        txtDiaChiNV.setRows(5);
        txtDiaChiNV.setWrapStyleWord(true);
        txtDiaChiNV.setAutoscrolls(false);
        txtDiaChiNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiaChiNVKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtDiaChiNV);

        dateChooser1.setCalendarBackground(new java.awt.Color(133, 140, 148));
        dateChooser1.setFieldFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 15));
        dateChooser1.setNavigateFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11));
        dateChooser1.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_PERIOD);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaNV)
                    .addComponent(txtTenNV)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(txtSDTNV, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(dateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNV)
                    .addComponent(jLabel9)
                    .addComponent(txtMatKhau)
                    .addComponent(jLabel10))
                .addGap(17, 17, 17)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTenNV)
                    .addComponent(jLabel12)
                    .addComponent(txtSDTNV))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel15)))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(71, 71, 71))))
        );

        jPanel10.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        btnThemNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnThemNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_plus_+_30px_1.png"))); // NOI18N
        btnThemNV.setText("Thêm");
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel13.add(btnThemNV, gridBagConstraints);

        btnSuaNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSuaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_edit_file_30px.png"))); // NOI18N
        btnSuaNV.setText("Sửa");
        btnSuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel13.add(btnSuaNV, gridBagConstraints);

        btnXoaNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnXoaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_30px.png"))); // NOI18N
        btnXoaNV.setText("Xóa");
        btnXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel13.add(btnXoaNV, gridBagConstraints);

        btnTimKiemNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnTimKiemNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_30px.png"))); // NOI18N
        btnTimKiemNV.setText("Tìm kiếm");
        btnTimKiemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemNVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel13.add(btnTimKiemNV, gridBagConstraints);

        btnLamMoiNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnLamMoiNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_reset_30px.png"))); // NOI18N
        btnLamMoiNV.setText("Làm mới");
        btnLamMoiNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiNVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel13.add(btnLamMoiNV, gridBagConstraints);

        btnLuuNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnLuuNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_save_close_30px.png"))); // NOI18N
        btnLuuNV.setText("Lưu");
        btnLuuNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuNVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel13.add(btnLuuNV, gridBagConstraints);

        jPanel10.add(jPanel13, java.awt.BorderLayout.SOUTH);

        jPanel4.add(jPanel10, java.awt.BorderLayout.NORTH);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        tbNhanVien.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        tbNhanVien.setMinimumSize(new java.awt.Dimension(20, 20));
        tbNhanVien.setRowHeight(25);
        tbNhanVien.setSelectionBackground(new java.awt.Color(0, 255, 204));
        tbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhanVienMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbNhanVien);

        jPanel12.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Quản lý nhân viên");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 230, 47));

        lblQTV.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        lblQTV.setForeground(new java.awt.Color(255, 255, 255));
        lblQTV.setText("Xin chào");
        jPanel1.add(lblQTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 180, -1));

        lblTime.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("jLabel5");
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 180, -1));

        btnHome.setBackground(new java.awt.Color(0, 153, 153));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Trang chủ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_home_40px.png"))); // NOI18N

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(15, 15, 15))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 155, -1));

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        setColorHome(btnHome);
        this.setVisible(false);
        Run.Home();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        setColorHome(btnHome);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        resetColorHome(btnHome);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnLuuNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuNVActionPerformed
        // TODO add your handling code here:
        if(btnThemNV.isEnabled())
        {            
            try {
                String Name_PATTERN = "^[\\p{L}\\p{M}' \\.\\-]+$";
                Pattern p = Pattern.compile(Name_PATTERN);
                if(p.matcher(txtTenNV.getText()).find()){
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Tên nhân viên chỉ bao gồm chữ cái, xin nhập lại Tên Nhân Viên");
                    return;
                }
                StringBuffer sb = new StringBuffer();
                if(txtMaNV.getText().equals("")){
                    sb.append("Mã nhân viên không được trống");
                }
                if(sb.length()>0){
                    JOptionPane.showMessageDialog(this, sb);
                    return;
                }
                if(txtMatKhau.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Mật khẩu không được bỏ trống");
                    return;
                }
                try {
                    int n = Integer.parseInt(txtSDTNV.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Số điện thoại chỉ bao gồm chữ số, xin hãy nhập lai!");
                    return;
                }
                if(txtSDTNV.getText().length()>10 || txtSDTNV.getText().length()<10){
                    JOptionPane.showMessageDialog(this, "Số điện thoại phải có 10 số");
                    return;
                }
                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                dateChooser1.setDateFormat(df);
                Date NS =  df.parse(dateChooser1.getText());
                NhanVien nv = new NhanVien();
                nv.setIdNhanVien(txtMaNV.getText());
                nv.setPassword(argon2.hash(2,15*1024,1, txtMatKhau.getText().toCharArray()));
                nv.setHoTenNV(txtTenNV.getText());  
                nv.setNgaySinh(NS);
                nv.setDiaChi(txtDiaChiNV.getText());
                nv.setSDT(txtSDTNV.getText());                
                NhanVienDAO NVDAO = new NhanVienDAO();
                NVDAO.insert(nv);
                JOptionPane.showMessageDialog(this, "Thêm mới thành công");
                ShowdataNhanVien();
                
            } catch (Exception e) {
                if(e.getMessage().equals("Duplicate entry '"+txtMaNV.getText()+"' for key 'PRIMARY'")){
                    JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại vui lòng nhập lại");
                }
                System.err.println("Loi:" + e.getMessage());
            }
        }else if(btnSuaNV.isEnabled()){
                
            try {
                String Name_PATTERN = "^[\\p{L}\\p{M}' \\.\\-]+$";
                Pattern p = Pattern.compile(Name_PATTERN);
                if(p.matcher(txtTenNV.getText()).find()){
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Tên nhân viên chỉ bao gồm chữ cái, xin nhập lại Tên Nhân Viên");
                    return;
                }
                StringBuffer sb = new StringBuffer();
                if(txtMaNV.getText().equals("")){
                        sb.append("Mã nhân viên không được trống");

                }
                if(sb.length()>0){
                    JOptionPane.showMessageDialog(this, sb);
                    return;
                }
                try {
                    int n = Integer.parseInt(txtSDTNV.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Số điện thoại chỉ bao gồm chữ số, xin hãy nhập lai!");
                    return;
                }
                if(txtSDTNV.getText().length()>10 || txtSDTNV.getText().length()<10){
                    JOptionPane.showMessageDialog(this, "Số điện thoại phải có 10 số!");
                    return;
                }
                
                
                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                dateChooser1.setDateFormat(df);
                Date NS =  df.parse(dateChooser1.getText());
                NhanVien nv = new NhanVien();
                nv.setIdNhanVien(txtMaNV.getText());
                nv.setPassword(argon2.hash(2,15*1024,1, txtMatKhau.getText().toCharArray()));
                nv.setHoTenNV(txtTenNV.getText());  
                nv.setNgaySinh(NS);
                nv.setDiaChi(txtDiaChiNV.getText());
                nv.setSDT(txtSDTNV.getText());                
                NhanVienDAO nvdao = new NhanVienDAO();
                nvdao.update(nv);
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                ShowdataNhanVien();
            } catch (Exception e) {
                System.out.println(e.getMessage());
                e.printStackTrace();
            }
        }else if(btnXoaNV.isEnabled()){
            String ml = txtMaNV.getText();
            StringBuilder sb = new StringBuilder();
            if(ml.equals("")){
                JOptionPane.showMessageDialog(this, "Mã nhân viên không được trống");
            }
            else{
                NhanVienDAO nvdao = new NhanVienDAO();
                boolean kt = nvdao.delete(txtMaNV.getText());
                if(kt==true)
                {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                }else{
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                }
                ShowdataNhanVien();
            }
        }
    }//GEN-LAST:event_btnLuuNVActionPerformed

    private void btnSuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNVActionPerformed
        // TODO add your handling code here:
        btnThemNV.setEnabled(false);
        btnXoaNV.setEnabled(false);
        btnLuuNV.setEnabled(true);
        btnTimKiemNV.setEnabled(false);
    }//GEN-LAST:event_btnSuaNVActionPerformed

    private void btnLamMoiNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiNVActionPerformed
        // TODO add your handling code here:
        btnSuaNV.setEnabled(true);
        btnXoaNV.setEnabled(true);
        btnLuuNV.setEnabled(false);
        btnThemNV.setEnabled(true);
        btnTimKiemNV.setEnabled(true);
        txtMaNV.setText("");
        txtMatKhau.setText("");
        txtDiaChiNV.setText("");
        txtSDTNV.setText("");
        txtTenNV.setText("");
        dateChooser1.setText("");
        ShowdataNhanVien();
    }//GEN-LAST:event_btnLamMoiNVActionPerformed

    private void btnTimKiemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemNVActionPerformed
        // TODO add your handling code here:
        btnSuaNV.setEnabled(true);
        btnXoaNV.setEnabled(true);
        btnLuuNV.setEnabled(false);
        btnThemNV.setEnabled(false);
        if(txtMaNV.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Mã nhân viên không được trống");
        }
        try {
            cleardataNhanVien();
            NhanVienDAO dao = new NhanVienDAO();
            List<NhanVien> data = dao.Search(txtMaNV.getText());
            for (int i = 0; i < data.size(); i++) {
                String[] row = {
                data.get(i).getIdNhanVien(),
                data.get(i).getHoTenNV(),
                String.valueOf(data.get(i).getNgaySinh()),
                data.get(i).getDiaChi(),
                data.get(i).getSDT(),                
            };
            tbModelNhanVien.addRow(row);
        }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Mã Nhân viên không tồn tại");
            
        }
    }//GEN-LAST:event_btnTimKiemNVActionPerformed

    private void btnXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNVActionPerformed
        // TODO add your handling code here:
        btnSuaNV.setEnabled(false);
        btnThemNV.setEnabled(false);
        btnLuuNV.setEnabled(true);
        btnTimKiemNV.setEnabled(false);
    }//GEN-LAST:event_btnXoaNVActionPerformed

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        // TODO add your handling code here:
        btnSuaNV.setEnabled(false);
        btnXoaNV.setEnabled(false);
        btnLuuNV.setEnabled(true);
        btnTimKiemNV.setEnabled(false);
    }//GEN-LAST:event_btnThemNVActionPerformed

    private void tbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhanVienMouseClicked
        // TODO add your handling code here:
        int row = tbNhanVien.getSelectedRow();
        if(row >= 0)
        {
            txtMaNV.setText(tbNhanVien.getValueAt(row, 0).toString());
            txtTenNV.setText(tbNhanVien.getValueAt(row, 1).toString());
            dateChooser1.setText(tbNhanVien.getValueAt(row, 2).toString());
            txtDiaChiNV.setText(tbNhanVien.getValueAt(row, 3).toString());
            txtSDTNV.setText(tbNhanVien.getValueAt(row, 4).toString());
        }
    }//GEN-LAST:event_tbNhanVienMouseClicked

    private void txtMaNVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaNVKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtTenNV.requestFocus();
        }
    }//GEN-LAST:event_txtMaNVKeyPressed

    private void txtTenNVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenNVKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtDiaChiNV.requestFocus();
        }
    }//GEN-LAST:event_txtTenNVKeyPressed

    private void txtDiaChiNVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaChiNVKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtMatKhau.requestFocus();
        }
    }//GEN-LAST:event_txtDiaChiNVKeyPressed

    private void txtMatKhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtSDTNV.requestFocus();
        }
    }//GEN-LAST:event_txtMatKhauKeyPressed

    /**
     * @param args the command line arguments
     */
    public void setColorHome(JPanel panel){
        panel.setBackground(new Color(153,255,255));
    }
    
    public void resetColorHome(JPanel panel){
         panel.setBackground(new Color(0,153,153));
    }
    
    private void setFontTable(JTable t){
        Font myFont = new Font("Serif", Font.PLAIN, 16);
        JTableHeader hd1 = t.getTableHeader();
        hd1.setFont(myFont);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnHome;
    private javax.swing.JButton btnLamMoiNV;
    private javax.swing.JButton btnLuuNV;
    private javax.swing.JButton btnSuaNV;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnTimKiemNV;
    private javax.swing.JButton btnXoaNV;
    private datechooser.beans.DateChooserCombo dateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblQTV;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tbNhanVien;
    private javax.swing.JTextArea txtDiaChiNV;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtSDTNV;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
