/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import DAO.ChiTietPhieuMuonDAO;
import DAO.DanhMucDAO;
import DAO.DauSachDAO;
import DAO.DocGiaDAO;
import DAO.PhieuMuonDAO;
import DAO.SachDAO;
import Models.ChiTietPhieuMuon;
import Models.DanhMuc;
import Models.DauSach;
import Models.DocGia;
import Models.PhieuMuon;
import Models.Sach;
import Models.SachMuon;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import com.mycompany.testmysql.Run;
import java.awt.BorderLayout;
import java.awt.Font;
import static java.lang.Thread.sleep;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author ADMIN
 */
public class QuanLyMuonSach_UI extends javax.swing.JFrame {
    DocGiaDAO dgDAO = new DocGiaDAO();
    DauSachDAO dsDAO = new DauSachDAO();
    SachDAO sDAO = new SachDAO();
    PhieuMuonDAO pmDAO = new PhieuMuonDAO();
    ChiTietPhieuMuonDAO ctDAO = new ChiTietPhieuMuonDAO();
    JList<SachMuon> jListSach;
    DefaultListModel<SachMuon> dlm = new DefaultListModel<>();
    DefaultTableModel tableModelPhieu;
    /**
     * Creates new form QuanLyMuonSach_UI
     */
    public QuanLyMuonSach_UI() {
        initComponents();
        
        //Set tên NV
        String text = "Xin chào,"+Run.tk.getHoTenNV();
        lblQTV.setText(text);
        //Set thời gian
        Clock clock= new Clock(); 
        clock.start();
        
        loadDocGia();
        loadSach();
        LoadComboBox();
        
        jListSach = new JList<SachMuon>(dlm);
        jListSach.setSelectionMode(
        ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jListSach.setFont(new Font("Segoe UI", Font.PLAIN, 15));
        jPSachMuon.add(jListSach,BorderLayout.CENTER);
        
        //Set font table
        setFontTable(tblSach);
        setFontTable(tblDocGia);        
        setFontTable(tblDocGia1);
        setFontTable(tblPhieuMuon);
        setFontTable(tblChiTietPhieuMuon);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblQTV = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPaneMenu = new javax.swing.JTabbedPane();
        jPMuonSach = new javax.swing.JPanel();
        jDocGia = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblDocGia = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTimDG = new javax.swing.JTextField();
        btnLoadDG = new javax.swing.JPanel();
        lblaaa = new javax.swing.JLabel();
        jpPhieuMuon = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblTenDG = new javax.swing.JLabel();
        lblMaDG = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPSachMuon = new javax.swing.JPanel();
        btnXacNhan = new javax.swing.JButton();
        btnHuyBo = new javax.swing.JButton();
        btnXoaSach = new javax.swing.JButton();
        jPSach = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTimSach = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cbbDanhMuc = new javax.swing.JComboBox<>();
        btnLoadSach = new javax.swing.JPanel();
        lblaaa1 = new javax.swing.JLabel();
        jPTraSach = new javax.swing.JPanel();
        jDocGia1 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblDocGia1 = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTimDG1 = new javax.swing.JTextField();
        btnLoadDG1 = new javax.swing.JPanel();
        lblaaa2 = new javax.swing.JLabel();
        jpPhieuMuon1 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblTenDG1 = new javax.swing.JLabel();
        lblMaDG1 = new javax.swing.JLabel();
        lblNgaySinh1 = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        lblSDT1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPSachMuon1 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tblPhieuMuon = new javax.swing.JTable();
        dateChooser1 = new datechooser.beans.DateChooserCombo();
        btnSearchPhieu = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnReloadPhieu = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPSach1 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblChiTietPhieuMuon = new javax.swing.JTable();
        btn_TraSach = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        lblMaPhieu = new javax.swing.JLabel();
        lblNgayMuon = new javax.swing.JLabel();
        lblHanMuon = new javax.swing.JLabel();
        lblQuaHan = new javax.swing.JLabel();

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("10-03-1999");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("mit@gmail.com");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Quản lý mượn trả sách");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 320, 60));

        lblQTV.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        lblQTV.setForeground(new java.awt.Color(255, 255, 255));
        lblQTV.setText("Xin chào");
        jPanel1.add(lblQTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 160, 30));

        lblTime.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("jLabel5");
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 30, 150, -1));

        btnHome.setBackground(new java.awt.Color(0, 153, 153));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Trang chủ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_home_40px.png"))); // NOI18N

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(15, 15, 15))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 155, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTabbedPaneMenu.setBackground(new java.awt.Color(0, 153, 153));
        jTabbedPaneMenu.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPaneMenu.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPaneMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPaneMenu.setFocusCycleRoot(true);
        jTabbedPaneMenu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jTabbedPaneMenu.setInheritsPopupMenu(true);
        jTabbedPaneMenu.setMinimumSize(new java.awt.Dimension(57, 40));
        jTabbedPaneMenu.setName(""); // NOI18N
        jTabbedPaneMenu.setOpaque(true);
        jTabbedPaneMenu.setVerifyInputWhenFocusTarget(false);

        jPMuonSach.setBackground(new java.awt.Color(255, 255, 255));
        jPMuonSach.setForeground(new java.awt.Color(255, 255, 255));
        jPMuonSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jDocGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jDocGia.setForeground(new java.awt.Color(153, 153, 153));
        jDocGia.setPreferredSize(new java.awt.Dimension(450, 597));
        jDocGia.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane8.setBackground(new java.awt.Color(255, 255, 255));

        tblDocGia.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        tblDocGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Mã Khu vực", "Tên Khu vực"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDocGia.setMinimumSize(new java.awt.Dimension(20, 20));
        tblDocGia.setRowHeight(25);
        tblDocGia.setSelectionBackground(new java.awt.Color(0, 255, 204));
        tblDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDocGiaMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblDocGia);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jDocGia.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Danh sách độc giả");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel3.setText("Tìm độc giả :");

        txtTimDG.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtTimDG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimDGKeyReleased(evt);
            }
        });

        btnLoadDG.setBackground(new java.awt.Color(255, 255, 255));
        btnLoadDG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoadDG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoadDGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoadDGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoadDGMouseExited(evt);
            }
        });

        lblaaa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_refresh_30px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnLoadDGLayout = new javax.swing.GroupLayout(btnLoadDG);
        btnLoadDG.setLayout(btnLoadDGLayout);
        btnLoadDGLayout.setHorizontalGroup(
            btnLoadDGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLoadDGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblaaa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLoadDGLayout.setVerticalGroup(
            btnLoadDGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLoadDGLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblaaa)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtTimDG, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoadDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLoadDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTimDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jDocGia.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jpPhieuMuon.setBackground(new java.awt.Color(255, 255, 255));
        jpPhieuMuon.setPreferredSize(new java.awt.Dimension(450, 0));
        jpPhieuMuon.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("Phiếu mượn");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin độc giả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 16))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Tên độc giả : ");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Mã độc giả : ");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Email :");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Số điện thoại :");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Ngày sinh :");

        lblTenDG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTenDG.setText("...");

        lblMaDG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNgaySinh.setText("...");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setText("...");

        lblSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSDT.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaDG, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTenDG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblTenDG))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(lblMaDG)
                    .addComponent(lblEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(lblNgaySinh)
                    .addComponent(lblSDT))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 16))); // NOI18N

        jPSachMuon.setBackground(new java.awt.Color(255, 255, 255));
        jPSachMuon.setLayout(new java.awt.BorderLayout());
        jScrollPane1.setViewportView(jPSachMuon);

        btnXacNhan.setBackground(new java.awt.Color(0, 51, 204));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnHuyBo.setBackground(new java.awt.Color(255, 51, 102));
        btnHuyBo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnHuyBo.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyBo.setText("Hủy bỏ");
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });

        btnXoaSach.setBackground(new java.awt.Color(255, 51, 102));
        btnXoaSach.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnXoaSach.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaSach.setText("Xóa sách");
        btnXoaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnXoaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jpPhieuMuon.add(jPanel16, java.awt.BorderLayout.PAGE_START);

        jPSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPSach.setPreferredSize(new java.awt.Dimension(450, 656));
        jPSach.setLayout(new java.awt.BorderLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane9.setBackground(new java.awt.Color(255, 255, 255));

        tblSach.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Mã Khu vực", "Tên Khu vực"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSach.setMinimumSize(new java.awt.Dimension(20, 20));
        tblSach.setRowHeight(25);
        tblSach.setSelectionBackground(new java.awt.Color(0, 255, 204));
        tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSachMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tblSach);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPSach.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("Sách mượn");

        jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel16.setText("Tìm sách :");

        txtTimSach.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtTimSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimSachKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel19.setText("Danh mục sách : ");

        cbbDanhMuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbDanhMuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDanhMucActionPerformed(evt);
            }
        });

        btnLoadSach.setBackground(new java.awt.Color(255, 255, 255));
        btnLoadSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoadSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoadSachMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoadSachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoadSachMouseExited(evt);
            }
        });

        lblaaa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_refresh_30px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnLoadSachLayout = new javax.swing.GroupLayout(btnLoadSach);
        btnLoadSach.setLayout(btnLoadSachLayout);
        btnLoadSachLayout.setHorizontalGroup(
            btnLoadSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLoadSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblaaa1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLoadSachLayout.setVerticalGroup(
            btnLoadSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLoadSachLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblaaa1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTimSach, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoadSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel15)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLoadSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(cbbDanhMuc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtTimSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPSach.add(jPanel15, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPMuonSachLayout = new javax.swing.GroupLayout(jPMuonSach);
        jPMuonSach.setLayout(jPMuonSachLayout);
        jPMuonSachLayout.setHorizontalGroup(
            jPMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMuonSachLayout.createSequentialGroup()
                .addComponent(jDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPMuonSachLayout.setVerticalGroup(
            jPMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPaneMenu.addTab("Quản lý mượn sách", new javax.swing.ImageIcon(getClass().getResource("/images/icons8_list_20px.png")), jPMuonSach); // NOI18N

        jPTraSach.setBackground(new java.awt.Color(255, 255, 255));
        jPTraSach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDocGia1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jDocGia1.setForeground(new java.awt.Color(153, 153, 153));
        jDocGia1.setPreferredSize(new java.awt.Dimension(450, 597));
        jDocGia1.setLayout(new java.awt.BorderLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane10.setBackground(new java.awt.Color(255, 255, 255));

        tblDocGia1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        tblDocGia1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Mã Khu vực", "Tên Khu vực"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDocGia1.setMinimumSize(new java.awt.Dimension(20, 20));
        tblDocGia1.setRowHeight(25);
        tblDocGia1.setSelectionBackground(new java.awt.Color(0, 255, 204));
        tblDocGia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDocGia1MouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(tblDocGia1);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDocGia1.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Danh sách độc giả");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel6.setText("Tìm độc giả :");

        txtTimDG1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtTimDG1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimDG1KeyReleased(evt);
            }
        });

        btnLoadDG1.setBackground(new java.awt.Color(255, 255, 255));
        btnLoadDG1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoadDG1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoadDG1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoadDG1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoadDG1MouseExited(evt);
            }
        });

        lblaaa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_refresh_30px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnLoadDG1Layout = new javax.swing.GroupLayout(btnLoadDG1);
        btnLoadDG1.setLayout(btnLoadDG1Layout);
        btnLoadDG1Layout.setHorizontalGroup(
            btnLoadDG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLoadDG1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblaaa2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLoadDG1Layout.setVerticalGroup(
            btnLoadDG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLoadDG1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblaaa2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtTimDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoadDG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLoadDG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTimDG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jDocGia1.add(jPanel18, java.awt.BorderLayout.PAGE_START);

        jPTraSach.add(jDocGia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 405, 656));

        jpPhieuMuon1.setBackground(new java.awt.Color(255, 255, 255));
        jpPhieuMuon1.setPreferredSize(new java.awt.Dimension(450, 0));
        jpPhieuMuon1.setLayout(new java.awt.BorderLayout());

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 102));
        jLabel24.setText("Phiếu mượn");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin độc giả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 16))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Tên độc giả : ");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Mã độc giả : ");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Email :");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Số điện thoại :");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("Ngày sinh :");

        lblTenDG1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblMaDG1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNgaySinh1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblEmail1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblSDT1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(lblTenDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNgaySinh1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmail1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSDT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMaDG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lblTenDG1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(lblMaDG1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(lblNgaySinh1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(lblEmail1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(lblSDT1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phiếu mượn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 16))); // NOI18N
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPSachMuon1.setBackground(new java.awt.Color(255, 255, 255));
        jPSachMuon1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane12.setBackground(new java.awt.Color(255, 255, 255));

        tblPhieuMuon.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        tblPhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Mã Khu vực", "Tên Khu vực"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhieuMuon.setMinimumSize(new java.awt.Dimension(20, 20));
        tblPhieuMuon.setRowHeight(25);
        tblPhieuMuon.setSelectionBackground(new java.awt.Color(0, 255, 204));
        tblPhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuMuonMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(tblPhieuMuon);

        jPSachMuon1.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 290, 250));

        dateChooser1.setCalendarBackground(new java.awt.Color(133, 140, 148));
        dateChooser1.setFieldFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 15));
        dateChooser1.setNavigateFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11));
        dateChooser1.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_PERIOD);
        jPSachMuon1.add(dateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        btnSearchPhieu.setBackground(new java.awt.Color(255, 255, 255));
        btnSearchPhieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchPhieuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchPhieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchPhieuMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_25px.png"))); // NOI18N

        javax.swing.GroupLayout btnSearchPhieuLayout = new javax.swing.GroupLayout(btnSearchPhieu);
        btnSearchPhieu.setLayout(btnSearchPhieuLayout);
        btnSearchPhieuLayout.setHorizontalGroup(
            btnSearchPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSearchPhieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSearchPhieuLayout.setVerticalGroup(
            btnSearchPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSearchPhieuLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPSachMuon1.add(btnSearchPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 40));

        btnReloadPhieu.setBackground(new java.awt.Color(255, 255, 255));
        btnReloadPhieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReloadPhieuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReloadPhieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReloadPhieuMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_reset_25px.png"))); // NOI18N

        javax.swing.GroupLayout btnReloadPhieuLayout = new javax.swing.GroupLayout(btnReloadPhieu);
        btnReloadPhieu.setLayout(btnReloadPhieuLayout);
        btnReloadPhieuLayout.setHorizontalGroup(
            btnReloadPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReloadPhieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnReloadPhieuLayout.setVerticalGroup(
            btnReloadPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnReloadPhieuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPSachMuon1.add(btnReloadPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 40));

        jScrollPane2.setViewportView(jPSachMuon1);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel19Layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(jLabel24))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jpPhieuMuon1.add(jPanel19, java.awt.BorderLayout.PAGE_START);

        jPTraSach.add(jpPhieuMuon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 0, 310, 656));

        jPSach1.setBackground(new java.awt.Color(255, 255, 255));
        jPSach1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPSach1.setPreferredSize(new java.awt.Dimension(450, 656));
        jPSach1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane11.setBackground(new java.awt.Color(255, 255, 255));

        tblChiTietPhieuMuon.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        tblChiTietPhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đầu sách", "Mã sách", "Tên sách", "Tác giả", "Tình trạng", "Tiền phạt", "Check"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChiTietPhieuMuon.setMinimumSize(new java.awt.Dimension(20, 20));
        tblChiTietPhieuMuon.setRowHeight(25);
        tblChiTietPhieuMuon.setSelectionBackground(new java.awt.Color(0, 255, 204));
        tblChiTietPhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietPhieuMuonMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tblChiTietPhieuMuon);

        btn_TraSach.setBackground(new java.awt.Color(0, 153, 0));
        btn_TraSach.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btn_TraSach.setForeground(new java.awt.Color(255, 255, 255));
        btn_TraSach.setText("Trả sách");
        btn_TraSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TraSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btn_TraSach))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_TraSach, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPSach1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 175, 620, 480));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));

        jLabel32.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 102));
        jLabel32.setText("Chi tiết phiếu mượn");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setText("Mã phiếu : ");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setText("Ngày mượn :");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setText("Hạn mượn :");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("Ghi chú :");

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGhiChu.setLineWrap(true);
        txtGhiChu.setRows(5);
        txtGhiChu.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtGhiChu);

        lblMaPhieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaPhieu.setText("DG0001");

        lblNgayMuon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNgayMuon.setText("DG0001");

        lblHanMuon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHanMuon.setText("DG0001");

        lblQuaHan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuaHan.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(200, 200, 200))
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(26, 26, 26)
                                .addComponent(lblMaPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNgayMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel36))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(lblHanMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuaHan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(lblMaPhieu)
                            .addComponent(jLabel36))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(lblNgayMuon))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(lblHanMuon)
                            .addComponent(lblQuaHan)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPSach1.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 11, 600, 160));

        jPTraSach.add(jPSach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 610, -1));

        jTabbedPaneMenu.addTab("Quản lý trả sách    ", new javax.swing.ImageIcon(getClass().getResource("/images/icons8_book_20px.png")), jPTraSach); // NOI18N

        getContentPane().add(jTabbedPaneMenu, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
    public class Clock extends Thread{ 
    public Clock(){    } 
    @Override
    public void run(){ 
        while(true){ 
            Calendar calendar = Calendar.getInstance();                
            String str;  
            str= sdf.format(calendar.getTime()); 
            lblTime.setText(str); 
        try{ 
            sleep(1000); 
          } catch(Exception e){ 
             System.out.println(e); 
            } 
      } 
    }
    }
    
    
    private void loadDocGia(){
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Mã độc giả");        
        tableModel.addColumn("Tên độc giả");        
        tableModel.addColumn("Ngày sinh");   
        
        List<DocGia> lstSP = dgDAO.getAllDocGia();
        for(DocGia sp : lstSP){
            tableModel.addRow(new Object[]{sp.getMaDocGia(),sp.getHoTen(),sp.getNgaySinh()});
        }
        tblDocGia.setModel(tableModel);        
        tblDocGia1.setModel(tableModel);

    }
    
    private void loadSach(){
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Mã sách");        
        tableModel.addColumn("Tên sách");        
        tableModel.addColumn("Tác giả");          
        tableModel.addColumn("Nhà xuất bản");   
 
        
        List<DauSach> lstSP = dsDAO.getDauSach();
        for(DauSach sp : lstSP){
            tableModel.addRow(new Object[]{sp.getMaSach(),sp.getTenSach(),sp.getTacGia(),sp.getNhaXuatBan()});
        }
        tblSach.setModel(tableModel);
    }
    
    public void LoadComboBox(){
        DanhMucDAO dm = new DanhMucDAO();
        Vector result = dm.getDM();
        if(result != null){
            DefaultComboBoxModel cbbmodel = new DefaultComboBoxModel(result);
            cbbDanhMuc.setModel(cbbmodel);    
        }else{
            JOptionPane.showMessageDialog(this, "Khong co danh muc nao");
        }
    }
    
    private void LoadSachByMaDM(int ma) {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Mã sách");        
        tableModel.addColumn("Tên sách");        
        tableModel.addColumn("Tác giả");          
        tableModel.addColumn("Nhà xuất bản");   
 
        
        List<DauSach> lstSP = dsDAO.getDauSachByMaDM(ma);
        for(DauSach sp : lstSP){
            tableModel.addRow(new Object[]{sp.getMaSach(),sp.getTenSach(),sp.getTacGia(),sp.getNhaXuatBan()});
        }
        tblSach.setModel(tableModel);
    }
    
    private void txtTimDGKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimDGKeyReleased
        String ten = txtTimDG.getText();
        
        List<DocGia> lst = dgDAO.SearchByName(ten);
        if(lst!= null){
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.addColumn("Mã độc giả");        
            tableModel.addColumn("Tên độc giả");        
            tableModel.addColumn("Ngày sinh");   

            for(DocGia sp : lst){
                tableModel.addRow(new Object[]{sp.getMaDocGia(),sp.getHoTen(),sp.getNgaySinh()});
            }
            tblDocGia.setModel(tableModel);
        }else{
            JOptionPane.showMessageDialog(null, "Không load dc !");
        }
    }//GEN-LAST:event_txtTimDGKeyReleased

    private void txtTimSachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimSachKeyReleased
        String ten = txtTimSach.getText();
        List<DauSach> lst = dsDAO.TimDauSachByTen(ten);
        if(lst!= null){
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.addColumn("Mã sách");        
            tableModel.addColumn("Tên sách");        
            tableModel.addColumn("Tác giả");          
            tableModel.addColumn("Nhà xuất bản");   
            for(DauSach sp : lst){
                tableModel.addRow(new Object[]{sp.getMaSach(),sp.getTenSach(),sp.getTacGia(),sp.getNhaXuatBan()});
            }
            tblSach.setModel(tableModel);
        }else{
            JOptionPane.showMessageDialog(null, "Không load dc !");
        }
    }//GEN-LAST:event_txtTimSachKeyReleased

    private void btnLoadDGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadDGMouseEntered
        setColorHome(btnLoadDG);
    }//GEN-LAST:event_btnLoadDGMouseEntered

    private void btnLoadDGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadDGMouseExited
        resetColorHome(btnLoadDG);
    }//GEN-LAST:event_btnLoadDGMouseExited

    private void btnLoadDGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadDGMouseClicked
        loadDocGia();
        txtTimDG.setText("");
    }//GEN-LAST:event_btnLoadDGMouseClicked

    private void btnLoadSachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadSachMouseEntered
        setColorHome(btnLoadSach);
    }//GEN-LAST:event_btnLoadSachMouseEntered

    private void btnLoadSachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadSachMouseExited
        resetColorHome(btnLoadSach);
    }//GEN-LAST:event_btnLoadSachMouseExited

    private void btnLoadSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadSachMouseClicked
        loadSach();
        txtTimSach.setText("");
    }//GEN-LAST:event_btnLoadSachMouseClicked

    private void tblDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDocGiaMouseClicked
        if(lblMaDG.getText() != ""){
            JOptionPane.showMessageDialog(null, "Phải hủy bỏ phiếu hiện tại!");
            return;
        }
        
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy"); 
        int row = tblDocGia.getSelectedRow();
        if(row == -1) return;
        String maDG = (String) tblDocGia.getValueAt(row, 0);
        int response = JOptionPane.showConfirmDialog(this, "Xác nhận tạo phiếu mượn ?","Đồng ý",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
            DocGia dgMuon = dgDAO.getDocGiaByMa(maDG);
            lblMaDG.setText(dgMuon.getMaDocGia());
            lblTenDG.setText(dgMuon.getHoTen());
            lblEmail.setText(dgMuon.getEmail());
            lblNgaySinh.setText(dateFormat.format(dgMuon.getNgaySinh()));
            lblSDT.setText(dgMuon.getSDT());
            PhieuMuon pm = new PhieuMuon();
            pm.setMaDocGia(maDG);
            pm.setMaNV(Run.tk.getIdNhanVien());
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            Date date = new Date();
            pm.setNgayMuon(date);
            pm.setTrangThai(0);
            pmDAO.insert(pm);
        }else if(response == JOptionPane.NO_OPTION){
        }
        
    }//GEN-LAST:event_tblDocGiaMouseClicked

    private void cbbDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDanhMucActionPerformed
        int maDM = ((DanhMuc)cbbDanhMuc.getSelectedItem()).getMaDanhMuc();
        LoadSachByMaDM(maDM);
    }//GEN-LAST:event_cbbDanhMucActionPerformed

    private void tblSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMouseClicked
        int row = tblSach.getSelectedRow();
        if(row == -1) return;
        String maDS = (String) tblSach.getValueAt(row, 0);
        
        DLSoLuong sl = new DLSoLuong(this, true, maDS);
        sl.setVisible(true);
    }//GEN-LAST:event_tblSachMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        setColorHome(btnHome);
        this.setVisible(false);
        Run.Home();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        setColorHome(btnHome);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnHomeMouseExited

    private void tblDocGia1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDocGia1MouseClicked
        
        DefaultTableModel dm = (DefaultTableModel) tblChiTietPhieuMuon.getModel();
        int rowCount = dm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
                
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy"); 
        int row = tblDocGia1.getSelectedRow();
        if(row == -1) return;
        String maDG = (String) tblDocGia1.getValueAt(row, 0);
        int response = JOptionPane.showConfirmDialog(this, "Xác nhận lấy thông tin phiếu mượn ?","Đồng ý",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
            DocGia dgMuon = dgDAO.getDocGiaByMa(maDG);
            lblMaDG1.setText(dgMuon.getMaDocGia());
            lblTenDG1.setText(dgMuon.getHoTen());
            lblEmail1.setText(dgMuon.getEmail());
            lblNgaySinh1.setText(dateFormat.format(dgMuon.getNgaySinh()));
            lblSDT1.setText(dgMuon.getSDT());
            
            //Xử lý load thông tin phiếu mượn
            List<PhieuMuon> lstPm = pmDAO.getPhieuMuonByMaDG(maDG);
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.addColumn("Mã phiếu mượn");        
            tableModel.addColumn("Ngày mượn");          
            for(PhieuMuon sp : lstPm){
                tableModel.addRow(new Object[]{sp.getMaPhieuMuon(),sp.getNgayMuon()});
            }
            tblPhieuMuon.setModel(tableModel);
            
        }else if(response == JOptionPane.NO_OPTION){
        }
    }//GEN-LAST:event_tblDocGia1MouseClicked

    private void txtTimDG1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimDG1KeyReleased
        String ten = txtTimDG1.getText(); 
        List<DocGia> lst = dgDAO.SearchByName(ten);
        if(lst!= null){
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.addColumn("Mã độc giả");        
            tableModel.addColumn("Tên độc giả");        
            tableModel.addColumn("Ngày sinh");   

            for(DocGia sp : lst){
                tableModel.addRow(new Object[]{sp.getMaDocGia(),sp.getHoTen(),sp.getNgaySinh()});
            }
            tblDocGia1.setModel(tableModel);
        }else{
            JOptionPane.showMessageDialog(null, "Không load dc !");
        }
    }//GEN-LAST:event_txtTimDG1KeyReleased

    private void btnLoadDG1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadDG1MouseClicked
        setColorHome(btnLoadDG1);
        loadDocGia();
        txtTimDG1.setText("");
    }//GEN-LAST:event_btnLoadDG1MouseClicked

    private void btnLoadDG1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadDG1MouseEntered
        setColorHome(btnLoadDG1);
    }//GEN-LAST:event_btnLoadDG1MouseEntered

    private void btnLoadDG1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadDG1MouseExited
        resetColorHome(btnLoadDG1);
    }//GEN-LAST:event_btnLoadDG1MouseExited

    private void tblChiTietPhieuMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietPhieuMuonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblChiTietPhieuMuonMouseClicked

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        List<SachMuon> listSM = new ArrayList<SachMuon>();
        for (int i = 0; i < jListSach.getModel().getSize();i++ )
        {
            listSM.add(jListSach.getModel().getElementAt(i));
        }
        
        DLXacNhanMuon dlm = new DLXacNhanMuon(this, true, lblMaDG.getText(), listSM);
        dlm.setVisible(true);
        JOptionPane.showMessageDialog(null, "Thêm thành công!!");
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnXoaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSachActionPerformed
        List<SachMuon> OnList = jListSach.getSelectedValuesList();
        for(SachMuon i : OnList){
            sDAO.OnSach(i.getMaSach());
        }

        for (SachMuon o : jListSach.getSelectedValuesList())
        {
            ((DefaultListModel<SachMuon>)jListSach.getModel()).removeElement(o);
        }

        jListSach.setModel(dlm);
    }//GEN-LAST:event_btnXoaSachActionPerformed

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        pmDAO.deletePhieuByMaDG(lblMaDG.getText());

        lblMaDG.setText("");
        lblTenDG.setText("");
        lblEmail.setText("");
        lblNgaySinh.setText("");
        lblSDT.setText("");

        for (int i = 0; i < jListSach.getModel().getSize();i++ )
        {
            sDAO.OffSach(jListSach.getModel().getElementAt(i).getMaSach());
        }
        ((DefaultListModel<SachMuon>)jListSach.getModel()).removeAllElements();
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void tblPhieuMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuMuonMouseClicked
         DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy"); 
            int row = tblPhieuMuon.getSelectedRow();
            if(row == -1) return;
            int maPhieu = (int) tblPhieuMuon.getValueAt(row, 0);
            PhieuMuon pm = pmDAO.SearchPhieuByMa(maPhieu);
            lblMaPhieu.setText(String.valueOf(pm.getMaPhieuMuon()));
            lblHanMuon.setText(String.valueOf(pm.getHanMuon()));
            lblNgayMuon.setText(dateFormat.format(pm.getNgayMuon()));
            //Xu ly qua han
//             Calendar c1 = Calendar.getInstance();
//             Calendar c2 = Calendar.getInstance();
//             Date date1 = Date.valueOf("2011-06-15");
//             Date date2 = Date.valueOf("2011-07-30");
//
//            c1.setTime(date1);
//            c2.setTime(date2);
//            
//            
//            
            txtGhiChu.setText(pm.getGhiChu());
            
        //Dữ liệu cho bảng sách trả
        tableModelPhieu = new DefaultTableModel(){
            public Class getColumnClass(int column){
                if(column==6){
                    return Boolean.class;
                }
                else{
                    return String.class;
                }
            }
            @Override
            public boolean isCellEditable(int row, int column) {
             if (row >= 0 && column <= 3) return false;
             return true;                 
            }  
        };
        String header[] = new String[] { "Mã đầu sách", "Mã sách", "Tên sách",
      "Tác giả", "Tình trạng","Tiền phạt", "Check" };
        tableModelPhieu.setColumnIdentifiers(header);
        
        List<SachMuon> lstSach = sDAO.LoadSachByIdPhieuMuon(maPhieu);
        for(SachMuon i : lstSach){
            tableModelPhieu.addRow(new Object[]{i.getMaDS(),i.getMaSach(),i.getTenSach(),i.getTacGia(),"Tốt","",false});
        }
        tblChiTietPhieuMuon.setModel(tableModelPhieu);
        
        JComboBox combo = new JComboBox();
        combo.addItem("Tốt");        
        combo.addItem("Mất");
        combo.addItem("Hư hỏng");

        TableColumn col = tblChiTietPhieuMuon.getColumnModel().getColumn(4);
        col.setCellEditor(new DefaultCellEditor(combo));
    }//GEN-LAST:event_tblPhieuMuonMouseClicked

    private void btnSearchPhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchPhieuMouseClicked
        setColorHome(btnSearchPhieu);
        Date d1 = dateChooser1.getSelectedDate().getTime();
        String s1 = String.format("%1$tY-%1$tm-%1$td", d1);
        if(lblTenDG1.getText()!=""){
            List<PhieuMuon> lstPm = pmDAO.getPhieuMuonByMaDGNgayMuon((String) tblDocGia1.getValueAt(tblDocGia1.getSelectedRow(),0),s1);
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.addColumn("Mã phiếu mượn");        
            tableModel.addColumn("Ngày mượn");          
            for(PhieuMuon sp : lstPm){
                tableModel.addRow(new Object[]{sp.getMaPhieuMuon(),sp.getNgayMuon()});
                System.out.println(sp.getNgayMuon());                
                System.out.println(sp.getMaPhieuMuon());

            }
            tblPhieuMuon.setModel(tableModel);
        }else{
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn độc giả!!");
        }
    }//GEN-LAST:event_btnSearchPhieuMouseClicked

    private void btnSearchPhieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchPhieuMouseEntered
         setColorHome(btnSearchPhieu);
    }//GEN-LAST:event_btnSearchPhieuMouseEntered

    private void btnSearchPhieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchPhieuMouseExited
        resetColorHome(btnSearchPhieu);
    }//GEN-LAST:event_btnSearchPhieuMouseExited

    private void btnReloadPhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReloadPhieuMouseClicked
        setColorHome(btnReloadPhieu);
        LoadPhieuMuonByMaDG();
    }//GEN-LAST:event_btnReloadPhieuMouseClicked

    private void btnReloadPhieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReloadPhieuMouseEntered
        setColorHome(btnReloadPhieu);
    }//GEN-LAST:event_btnReloadPhieuMouseEntered

    private void btnReloadPhieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReloadPhieuMouseExited
        resetColorHome(btnReloadPhieu);
    }//GEN-LAST:event_btnReloadPhieuMouseExited

    private void btn_TraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TraSachActionPerformed
        if(tableModelPhieu.getRowCount()==0){JOptionPane.showMessageDialog(null, "Bạn chưa chọn phiếu mượn!!");}
        boolean check1 = false;        
        boolean check2 = false;

        int response = JOptionPane.showConfirmDialog(this, "Xác nhận trả sách?","Trả sách",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
            for (int i = 0; i < tableModelPhieu.getRowCount(); i++) {
                int idSach= Integer.parseInt(tableModelPhieu.getValueAt(i, 1).toString());
                int idPhieuMuon = Integer.parseInt(lblMaPhieu.getText());
                Date NgayTra = new Date();
                String TinhTrangSach = tableModelPhieu.getValueAt(i, 4).toString();
                float MucPhat = 0;
                if(tableModelPhieu.getValueAt(i, 5).toString() == ""){
                    MucPhat = 0;
                }else{
                    MucPhat = Float.parseFloat(tableModelPhieu.getValueAt(i, 5).toString());
                }
                ChiTietPhieuMuon ct = new ChiTietPhieuMuon(idSach,idPhieuMuon,NgayTra,TinhTrangSach,MucPhat);
                if(ctDAO.update(ct)){check1 = true;}
                //Set lại trạng thái sách
                if(tableModelPhieu.getValueAt(i, 4).toString() == "Tốt"){
                    sDAO.OnSach(Integer.parseInt(tableModelPhieu.getValueAt(i, 1).toString()));
                }else if(tableModelPhieu.getValueAt(i, 4).toString() == "Hư hỏng"){
                    sDAO.OffSach(Integer.parseInt(tableModelPhieu.getValueAt(i, 1).toString()));
                }else{
                    sDAO.OffSach(Integer.parseInt(tableModelPhieu.getValueAt(i, 1).toString()));
                }
                
                
                //Set trạng thái phiếu mượn
                
                String ghiChu = txtGhiChu.getText();
                if(pmDAO.UpdateTrangThaiHoanThanh(idPhieuMuon) && pmDAO.UpdateGhiChu(idPhieuMuon, ghiChu)){check2 = true;}
            }
        }
        if(check1 &&check2){
            JOptionPane.showMessageDialog(null, "Trả thành công!!");
            LoadPhieuMuonByMaDG();
            DefaultTableModel dm = (DefaultTableModel) tblChiTietPhieuMuon.getModel();
            int rowCount = dm.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                dm.removeRow(i);
            }
        }
    }//GEN-LAST:event_btn_TraSachActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setColorHome(JPanel panel){
        panel.setBackground(new Color(153,255,255));
    }
    
    public void resetColorHome(JPanel panel){
        panel.setBackground(Color.white);
    }
    
    public void LoadSachMuon(List<SachMuon> lst){
        
        for(SachMuon i : lst){
            dlm.addElement(i);
        }
        jListSach.setModel(dlm);
    }
    
    public void LoadPhieuMuonComlete(){
        lblMaDG.setText("");
        lblTenDG.setText("");
        lblEmail.setText("");
        lblNgaySinh.setText("");
        lblSDT.setText("");
        
        ((DefaultListModel<SachMuon>)jListSach.getModel()).removeAllElements();
    }
    
    public void LoadPhieuMuonByMaDG(){
        List<PhieuMuon> lstPm = pmDAO.getPhieuMuonByMaDG((String) tblDocGia1.getValueAt(tblDocGia1.getSelectedRow(),0));
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Mã phiếu mượn");        
        tableModel.addColumn("Ngày mượn");          
        for(PhieuMuon sp : lstPm){
            tableModel.addRow(new Object[]{sp.getMaPhieuMuon(),sp.getNgayMuon()});
        }
        tblPhieuMuon.setModel(tableModel);
    }
    private void setFontTable(JTable t){
        Font myFont = new Font("Serif", Font.PLAIN, 16);
        JTableHeader hd1 = t.getTableHeader();
        hd1.setFont(myFont);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnHome;
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JPanel btnLoadDG;
    private javax.swing.JPanel btnLoadDG1;
    private javax.swing.JPanel btnLoadSach;
    private javax.swing.JPanel btnReloadPhieu;
    private javax.swing.JPanel btnSearchPhieu;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoaSach;
    private javax.swing.JButton btn_TraSach;
    private javax.swing.JComboBox<String> cbbDanhMuc;
    private datechooser.beans.DateChooserCombo dateChooser1;
    private javax.swing.JPanel jDocGia;
    private javax.swing.JPanel jDocGia1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPMuonSach;
    private javax.swing.JPanel jPSach;
    private javax.swing.JPanel jPSach1;
    private javax.swing.JPanel jPSachMuon;
    private javax.swing.JPanel jPSachMuon1;
    private javax.swing.JPanel jPTraSach;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPaneMenu;
    private javax.swing.JPanel jpPhieuMuon;
    private javax.swing.JPanel jpPhieuMuon1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblHanMuon;
    private javax.swing.JLabel lblMaDG;
    private javax.swing.JLabel lblMaDG1;
    private javax.swing.JLabel lblMaPhieu;
    private javax.swing.JLabel lblNgayMuon;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNgaySinh1;
    private javax.swing.JLabel lblQTV;
    private javax.swing.JLabel lblQuaHan;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSDT1;
    private javax.swing.JLabel lblTenDG;
    private javax.swing.JLabel lblTenDG1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblaaa;
    private javax.swing.JLabel lblaaa1;
    private javax.swing.JLabel lblaaa2;
    private javax.swing.JTable tblChiTietPhieuMuon;
    private javax.swing.JTable tblDocGia;
    private javax.swing.JTable tblDocGia1;
    private javax.swing.JTable tblPhieuMuon;
    private javax.swing.JTable tblSach;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtTimDG;
    private javax.swing.JTextField txtTimDG1;
    private javax.swing.JTextField txtTimSach;
    // End of variables declaration//GEN-END:variables

    
}
